language: python
python:
  - "3.6"

sudo: true
dist: trusty

stages:
  - unit tests
  - integration tests

jobs:
  include:
    - stage: unit tests
      install:
        - python setup.py install
      script:
        - nosetests

    # there is no support of Matrix expansion per-stage, but this way it works
    # source: https://github.com/travis-ci/travis-ci/issues/8295

    - stage: integration tests
      env:
        - EOS_BRANCH=v1.4.1 PYTHON_VERSION=3.5.6
      script:
        - docker build -t e2e --build-arg eos_branch=${EOS_BRANCH} --build-arg eosfactory_branch=${TRAVIS_PULL_REQUEST_BRANCH} --build-arg python_version=${PYTHON_VERSION} ./tests/integration/
        - docker run -ti e2e "python /opt/eosfactory/tests/01_hello_world.py"
        - docker run -ti e2e "python /opt/eosfactory/tests/02_eosio_token.py"
        - docker run -ti e2e "python /opt/eosfactory/tests/03_tic_tac_toe.py"

    - stage: integration tests
      env:
        - EOS_BRANCH=v1.4.1 PYTHON_VERSION=3.6.6
      script:
        - docker build -t e2e --build-arg eos_branch=${EOS_BRANCH} --build-arg eosfactory_branch=${TRAVIS_PULL_REQUEST_BRANCH} --build-arg python_version=${PYTHON_VERSION} ./tests/integration/
        - docker run -ti e2e "python /opt/eosfactory/tests/01_hello_world.py"
        - docker run -ti e2e "python /opt/eosfactory/tests/02_eosio_token.py"
        - docker run -ti e2e "python /opt/eosfactory/tests/03_tic_tac_toe.py"

    - stage: integration tests
      env:
        - EOS_BRANCH=v1.4.1 PYTHON_VERSION=3.7.0
      script:
        - docker build -t e2e --build-arg eos_branch=${EOS_BRANCH} --build-arg eosfactory_branch=${TRAVIS_PULL_REQUEST_BRANCH} --build-arg python_version=${PYTHON_VERSION} ./tests/integration/
        - docker run -ti e2e "python /opt/eosfactory/tests/01_hello_world.py"
        - docker run -ti e2e "python /opt/eosfactory/tests/02_eosio_token.py"
        - docker run -ti e2e "python /opt/eosfactory/tests/03_tic_tac_toe.py"
